"""added is_assigned column to employee

Revision ID: 1a46665aa0e3
Revises: 33f94f06ce60
Create Date: 2026-06-24 11:10:00.986264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a46665aa0e3"
down_revision: str | Sequence[str] | None = "33f94f06ce60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column(
    #     "employees",
    #     sa.Column("is_assigned", sa.Boolean(), server_default="false", nullable=False),
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("employees", "is_assigned")

    # ### end Alembic commands ###
