"""added tables

Revision ID: 2928989b7801
Revises:
Create Date: 2026-07-05 05:47:36.089304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2928989b7801"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_pool_state",
        sa.Column("mailbox_address", sa.String(length=200), nullable=False),
        sa.Column("last_history_id", sa.String(length=50), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mailbox_address"),
    )
    op.create_table(
        "emails",
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=200), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=200), nullable=False),
        sa.Column("sender_email", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "classification_status",
            sa.Enum(
                "unknown", "timesheet", "not_timesheet", name="email_classification_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "classified",
                "extracted",
                "merged",
                "processed",
                "failed",
                name="email_status",
            ),
            nullable=False,
        ),
        sa.Column("failure_stage", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("email_id"),
        sa.UniqueConstraint("gmail_message_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role", sa.Enum("admin", "OpsAdmin", "reviewer", name="user_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "attachments",
        sa.Column("attachment_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("attachment_url", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "timesheet",
                "not_timesheet",
                "extracted",
                "failed",
                name="attachment_status",
            ),
            nullable=False,
        ),
        sa.Column("failure_stage", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.email_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attachment_id"),
    )
    op.create_table(
        "clients",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column("sender_email", sa.String(length=200), nullable=False),
        sa.Column("sender_domain", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "employees",
        sa.Column("emp_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_assigned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("emp_id"),
    )
    op.create_table(
        "timesheets",
        sa.Column("timesheet_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("week_ending", sa.Date(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "under_review", "processed", name="timesheet_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.email_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("timesheet_id"),
        sa.UniqueConstraint("email_id", name="uq_timesheet_email"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "content_extracts",
        sa.Column("content_extract_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("extracted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"], ["attachments.attachment_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.email_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("content_extract_id"),
        sa.UniqueConstraint(
            "email_id", "source_type", "attachment_id", name="uq_content_extract_source"
        ),
    )
    op.create_table(
        "departments",
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("department_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
        ),
        sa.PrimaryKeyConstraint("department_id"),
        sa.UniqueConstraint("client_id", "department_name", name="uq_department_client_name"),
    )
    op.create_table(
        "assignments",
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("emp_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "pay_rate", sa.Numeric(precision=10, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="assignment_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.department_id"],
        ),
        sa.ForeignKeyConstraint(
            ["emp_id"],
            ["employees.emp_id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id"),
    )
    op.create_index(
        "uq_employee_active_assignment",
        "assignments",
        ["emp_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "client_rules",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "weekly_ot_threshold",
            sa.Numeric(precision=5, scale=2),
            server_default="40",
            nullable=False,
        ),
        sa.Column("weekly_dt_threshold", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "ot_multiplier",
            sa.Numeric(precision=4, scale=2),
            server_default="1.5",
            nullable=False,
        ),
        sa.Column(
            "dt_multiplier",
            sa.Numeric(precision=4, scale=2),
            server_default="2.0",
            nullable=False,
        ),
        sa.Column("break_deduction_hrs", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("break_auto_deduct", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.client_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.department_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_table(
        "timecards",
        sa.Column("timecard_id", sa.UUID(), nullable=False),
        sa.Column("timesheet_id", sa.UUID(), nullable=False),
        sa.Column("emp_id", sa.UUID(), nullable=True),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("week_ending", sa.Date(), nullable=False),
        sa.Column("employee_name", sa.String(length=200), nullable=True),
        sa.Column("reg_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("ot_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("dt_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("pay_rate", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("regular_pay", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("ot_pay", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("dt_pay", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("gross_pay", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "no_exception",
                "exception",
                "approved",
                "rejected",
                name="timecard_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("none", "low", "medium", "high", name="exception_severity"),
            server_default="none",
            nullable=False,
        ),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.assignment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["emp_id"],
            ["employees.emp_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["client_rules.rule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["timesheet_id"], ["timesheets.timesheet_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("timecard_id"),
    )
    op.create_table(
        "exceptions",
        sa.Column("exception_id", sa.UUID(), nullable=False),
        sa.Column("timecard_id", sa.UUID(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("none", "low", "medium", "high", name="exception_severity"),
            nullable=False,
        ),
        sa.Column(
            "exception_type",
            sa.Enum(
                "employee_not_found",
                "missing_employee_id",
                "missing_assignment_id",
                "hours_exceed_limit",
                "weekly_hours_exceed_limit",
                "low_confidence",
                "calculation_discrepancy",
                "time_entry_conflict",
                "missing_time_entry",
                name="exception_type",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["timecard_id"], ["timecards.timecard_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("exception_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exceptions")
    op.drop_table("timecards")
    op.drop_table("client_rules")
    op.drop_index(
        "uq_employee_active_assignment",
        table_name="assignments",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("assignments")
    op.drop_table("departments")
    op.drop_table("content_extracts")
    op.drop_table("user_sessions")
    op.drop_table("timesheets")
    op.drop_table("employees")
    op.drop_table("clients")
    op.drop_table("attachments")
    op.drop_table("users")
    op.drop_table("emails")
    op.drop_table("email_pool_state")
    # ### end Alembic commands ###
