"""addded payload

Revision ID: 3aa7f099d031
Revises: b7f1a4d2c9e8
Create Date: 2026-06-30 15:10:49.297084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3aa7f099d031"
down_revision: Union[str, Sequence[str], None] = "b7f1a4d2c9e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timesheets",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("timesheets", "enriched_payload")
    op.drop_column("timesheets", "merged_payload")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timesheets",
        sa.Column(
            "merged_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "timesheets",
        sa.Column(
            "enriched_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("timesheets", "payload")
    # ### end Alembic commands ###
