"""added timesheet table

Revision ID: 4c2514039911
Revises: 3c08bdd78058
Create Date: 2026-06-22 05:27:01.774719

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c2514039911"
down_revision: str | Sequence[str] | None = "3c08bdd78058"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timesheets",
        sa.Column("timesheet_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=True),
        sa.Column("week_ending", sa.Date(), nullable=True),
        sa.Column(
            "extracted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "status", sa.String(length=50), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"], ["attachments.attachment_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.email_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("timesheet_id"),
        sa.UniqueConstraint(
            "email_id", "source_type", "attachment_id", name="uq_timesheet_source"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timesheets")
    # ### end Alembic commands ###
