"""added content_extract

Revision ID: 4f1f0b35d823
Revises: a24d77e735c3
Create Date: 2026-06-25 11:00:31.392484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f1f0b35d823"
down_revision: str | Sequence[str] | None = "a24d77e735c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    timesheet_status = postgresql.ENUM(
        "PENDING",
        "MERGING",
        "COMPLETED",
        name="timesheet_status",
    )

    timesheet_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_extracts",
        sa.Column("content_extract_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("attachment_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("extracted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", name="content_extract_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attachment_id"], ["attachments.attachment_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.email_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("content_extract_id"),
        sa.UniqueConstraint(
            "email_id", "source_type", "attachment_id", name="uq_content_extract_source"
        ),
    )
    op.add_column(
        "timesheets",
        sa.Column("merged_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "timesheets",
        sa.Column(
            "merge_status",
            sa.Enum("PENDING", "MERGING", "COMPLETED", name="timesheet_status"),
            server_default="PENDING",
            nullable=False,
        ),
    )
    op.add_column(
        "timesheets",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("uq_timesheet_source"), "timesheets", type_="unique")
    op.create_unique_constraint("uq_timesheet_email", "timesheets", ["email_id"])
    op.drop_constraint(op.f("timesheets_attachment_id_fkey"), "timesheets", type_="foreignkey")
    op.drop_column("timesheets", "extracted_payload")
    op.drop_column("timesheets", "source_type")
    op.drop_column("timesheets", "attachment_id")
    op.drop_column("timesheets", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timesheets",
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'pending'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "timesheets", sa.Column("attachment_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "timesheets",
        sa.Column("source_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "timesheets",
        sa.Column(
            "extracted_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("timesheets_attachment_id_fkey"),
        "timesheets",
        "attachments",
        ["attachment_id"],
        ["attachment_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_timesheet_email", "timesheets", type_="unique")
    op.create_unique_constraint(
        op.f("uq_timesheet_source"),
        "timesheets",
        ["email_id", "source_type", "attachment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("timesheets", "updated_at")
    op.drop_column("timesheets", "merge_status")
    op.drop_column("timesheets", "merged_payload")
    op.drop_table("content_extracts")
    content_extract_status = sa.Enum(name="content_extract_status")
    content_extract_status.drop(op.get_bind(), checkfirst=True)

    timesheet_status = sa.Enum(name="timesheet_status")
    timesheet_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
