"""added is_active to deparment

Revision ID: a24d77e735c3
Revises: c19a613c2713
Create Date: 2026-06-24 14:18:37.978079

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a24d77e735c3"
down_revision: str | Sequence[str] | None = "c19a613c2713"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "departments",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("departments", "is_active")
    # ### end Alembic commands ###
