"""added assignment,employee,client,department tables

Revision ID: c0f7c5936658
Revises: 4c2514039911
Create Date: 2026-06-23 14:58:57.020820

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0f7c5936658"
down_revision: str | Sequence[str] | None = "4c2514039911"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column("sender_email", sa.String(length=200), nullable=True),
        sa.Column("sender_domain", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "employees",
        sa.Column("emp_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("emp_id"),
    )
    op.create_table(
        "departments",
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("department_name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
        ),
        sa.PrimaryKeyConstraint("department_id"),
        sa.UniqueConstraint("client_id", "department_name", name="uq_department_client_name"),
    )
    op.create_table(
        "assignments",
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("emp_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="assignment_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.department_id"],
        ),
        sa.ForeignKeyConstraint(
            ["emp_id"],
            ["employees.emp_id"],
        ),
        sa.PrimaryKeyConstraint("assignment_id"),
    )
    op.create_index(
        "uq_employee_active_assignment",
        "assignments",
        ["emp_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "uq_employee_active_assignment",
        table_name="assignments",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("assignments")
    op.drop_table("departments")
    op.drop_table("employees")
    op.drop_table("clients")
    # ### end Alembic commands ###
