"""added email_pool_state

Revision ID: c19a613c2713
Revises: 1a46665aa0e3
Create Date: 2026-06-24 11:21:09.532503

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c19a613c2713"
down_revision: str | Sequence[str] | None = "1a46665aa0e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_pool_state",
        sa.Column("mailbox_address", sa.String(length=200), nullable=False),
        sa.Column("last_history_id", sa.String(length=50), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mailbox_address"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_pool_state")
    # ### end Alembic commands ###
