"""addded client rules,timecard,exception

Revision ID: c85ab4f4a000
Revises: d3db4451fbf1
Create Date: 2026-06-29 05:03:13.586947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c85ab4f4a000"
down_revision: str | Sequence[str] | None = "d3db4451fbf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_rules",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column(
            "weekly_ot_threshold",
            sa.Numeric(precision=5, scale=2),
            server_default="40",
            nullable=False,
        ),
        sa.Column("weekly_dt_threshold", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "ot_multiplier",
            sa.Numeric(precision=4, scale=2),
            server_default="1.5",
            nullable=False,
        ),
        sa.Column(
            "dt_multiplier",
            sa.Numeric(precision=4, scale=2),
            server_default="2.0",
            nullable=False,
        ),
        sa.Column("break_deduction_hrs", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("break_auto_deduct", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.client_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.department_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_table(
        "timecards",
        sa.Column("timecard_id", sa.UUID(), nullable=False),
        sa.Column("timesheet_id", sa.UUID(), nullable=False),
        sa.Column("emp_id", sa.UUID(), nullable=True),
        sa.Column("assignment_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("week_ending", sa.Date(), nullable=False),
        sa.Column("employee_name", sa.String(length=200), nullable=True),
        sa.Column("reg_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("ot_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("dt_hours", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "clean", "exception", "approved", "rejected", name="timecard_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("none", "low", "medium", "high", name="exception_severity"),
            server_default="none",
            nullable=False,
        ),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.assignment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["emp_id"],
            ["employees.emp_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["client_rules.rule_id"],
        ),
        sa.ForeignKeyConstraint(
            ["timesheet_id"], ["timesheets.timesheet_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("timecard_id"),
        sa.UniqueConstraint(
            "emp_id", "assignment_id", "week_ending", name="uq_timecard_employee_week"
        ),
    )
    op.create_table(
        "exceptions",
        sa.Column("exception_id", sa.UUID(), nullable=False),
        sa.Column("timecard_id", sa.UUID(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("none", "low", "medium", "high", name="exception_severity"),
            nullable=False,
        ),
        sa.Column(
            "exception_type",
            sa.Enum(
                "employee_not_found",
                "hours_exceed_limit",
                "low_confidence",
                "calculation_discrepancy",
                "missing_time_entry",
                name="exception_type",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["timecard_id"], ["timecards.timecard_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("exception_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exceptions")
    op.drop_table("timecards")
    op.drop_table("client_rules")
    # ### end Alembic commands ###
