"""addded under_review status to timesheet

Revision ID: d3db4451fbf1
Revises: dee1236e823a
Create Date: 2026-06-28 07:52:22.477484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d3db4451fbf1"
down_revision: str | Sequence[str] | None = "dee1236e823a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_extracts", "status")
    op.execute("ALTER TYPE timesheet_status ADD VALUE IF NOT EXISTS 'under_review';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_extracts",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "PROCESSING", "COMPLETED", name="content_extract_status"
            ),
            server_default=sa.text("'PENDING'::content_extract_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
