"""addded enriched_payload column to timesheet

Revision ID: dee1236e823a
Revises: cd1512263fb7
Create Date: 2026-06-27 19:00:13.123040

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dee1236e823a"
down_revision: str | Sequence[str] | None = "cd1512263fb7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timesheets",
        sa.Column("enriched_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timesheets", "enriched_payload")
    # ### end Alembic commands ###
