"""modified email,attachment,timesheet status

Revision ID: ed8ae0e7e6e2
Revises: 4f1f0b35d823
Create Date: 2026-06-26 22:26:47.377087

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed8ae0e7e6e2"
down_revision: str | Sequence[str] | None = "4f1f0b35d823"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # -------------------------
    # Email Status
    # -------------------------
    op.execute("""
        CREATE TYPE email_status_new AS ENUM (
            'received',
            'classified',
            'extracted',
            'merged',
            'failed'
        );
    """)

    op.execute("""
        ALTER TABLE emails
        ALTER COLUMN status
        TYPE email_status_new
        USING (
            CASE
                WHEN status::text = 'processed' THEN 'merged'
                WHEN status::text = 'not_processed' THEN 'received'
                WHEN status::text = 'not_received' THEN 'received'
                ELSE status::text
            END
        )::email_status_new;
    """)

    op.execute("DROP TYPE email_status;")
    op.execute("ALTER TYPE email_status_new RENAME TO email_status;")

    # -------------------------
    # Attachment Status
    # -------------------------
    op.execute("""
        CREATE TYPE attachment_status_new AS ENUM (
            'pending',
            'timesheet',
            'not_timesheet',
            'extracted',
            'failed'
        );
    """)

    op.execute("""
        ALTER TABLE attachments
        ALTER COLUMN status
        TYPE attachment_status_new
        USING (
            CASE
                WHEN status::text = 'processed' THEN 'extracted'
                WHEN status::text = 'not_processed' THEN 'pending'
                ELSE status::text
            END
        )::attachment_status_new;
    """)

    op.execute("DROP TYPE attachment_status;")
    op.execute("ALTER TYPE attachment_status_new RENAME TO attachment_status;")

    op.add_column(
        "timesheets",
        sa.Column(
            "status",
            sa.Enum("PENDING", "processed", name="timesheet_status"),
            server_default="PENDING",
            nullable=False,
        ),
    )
    op.drop_column("timesheets", "merge_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timesheets",
        sa.Column(
            "merge_status",
            postgresql.ENUM("PENDING", "MERGING", "COMPLETED", name="timesheet_status"),
            server_default=sa.text("'PENDING'::timesheet_status"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("timesheets", "status")
    # ### end Alembic commands ###
