"""created users,email_pool_state, emails,attachments table

Revision ID: fa4429c33cee
Revises:
Create Date: 2026-06-17 03:07:06.757093

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa4429c33cee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_pool_state",
        sa.Column("mailbox_address", sa.String(length=200), nullable=False),
        sa.Column("last_history_id", sa.String(length=50), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mailbox_address"),
    )
    op.create_table(
        "emails",
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=200), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=200), nullable=False),
        sa.Column("sender_email", sa.String(length=200), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "CLASSIFYING",
                "TIMESHEET_DETECTED",
                "NOT_TIMESHEET",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                name="email_status",
            ),
            nullable=False,
        ),
        sa.Column("failure_stage", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("email_id"),
        sa.UniqueConstraint("gmail_message_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "OpsAdmin", "reviewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "attachments",
        sa.Column("attachment_id", sa.UUID(), nullable=False),
        sa.Column("email_id", sa.UUID(), nullable=False),
        sa.Column("attachment_url", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "NOT_SUPPORTED_DOCUMENT",
                "TIMESHEET",
                "NOT_TIMESHEET",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                name="attachment_status",
            ),
            nullable=False,
        ),
        sa.Column("failure_stage", sa.String(length=100), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["email_id"], ["emails.email_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attachment_id"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_sessions")
    op.drop_table("attachments")
    op.drop_table("users")
    op.drop_table("emails")
    op.drop_table("email_pool_state")
    # ### end Alembic commands ###
